# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Base_Interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 493)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabs_master = QtGui.QTabWidget(self.centralwidget)
        self.tabs_master.setGeometry(QtCore.QRect(150, 40, 491, 351))
        self.tabs_master.setObjectName(_fromUtf8("tabs_master"))
        self.tab_modeling = QtGui.QWidget()
        self.tab_modeling.setObjectName(_fromUtf8("tab_modeling"))
        self.mdl_grp_scan = QtGui.QGroupBox(self.tab_modeling)
        self.mdl_grp_scan.setGeometry(QtCore.QRect(20, 20, 191, 281))
        self.mdl_grp_scan.setObjectName(_fromUtf8("mdl_grp_scan"))
        self.layoutWidget = QtGui.QWidget(self.mdl_grp_scan)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 141, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chk_mdl_transformation = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_transformation.setObjectName(_fromUtf8("chk_mdl_transformation"))
        self.verticalLayout.addWidget(self.chk_mdl_transformation)
        self.chk_mdl_history = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_history.setObjectName(_fromUtf8("chk_mdl_history"))
        self.verticalLayout.addWidget(self.chk_mdl_history)
        self.chk_mdl_hierarchy = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_hierarchy.setAutoFillBackground(False)
        self.chk_mdl_hierarchy.setObjectName(_fromUtf8("chk_mdl_hierarchy"))
        self.verticalLayout.addWidget(self.chk_mdl_hierarchy)
        self.chk_mdl_names = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_names.setObjectName(_fromUtf8("chk_mdl_names"))
        self.verticalLayout.addWidget(self.chk_mdl_names)
        self.chk_mdl_materials = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_materials.setObjectName(_fromUtf8("chk_mdl_materials"))
        self.verticalLayout.addWidget(self.chk_mdl_materials)
        self.chk_mdl_uvSets = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_uvSets.setObjectName(_fromUtf8("chk_mdl_uvSets"))
        self.verticalLayout.addWidget(self.chk_mdl_uvSets)
        self.chk_mdl_center = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_center.setObjectName(_fromUtf8("chk_mdl_center"))
        self.verticalLayout.addWidget(self.chk_mdl_center)
        self.chk_mdl_unknown = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_unknown.setAutoFillBackground(False)
        self.chk_mdl_unknown.setObjectName(_fromUtf8("chk_mdl_unknown"))
        self.verticalLayout.addWidget(self.chk_mdl_unknown)
        self.chk_mdl_invalidNames = QtGui.QCheckBox(self.layoutWidget)
        self.chk_mdl_invalidNames.setObjectName(_fromUtf8("chk_mdl_invalidNames"))
        self.verticalLayout.addWidget(self.chk_mdl_invalidNames)
        self.mdl_grp_fix = QtGui.QGroupBox(self.tab_modeling)
        self.mdl_grp_fix.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix.setObjectName(_fromUtf8("mdl_grp_fix"))
        self.scrollArea = QtGui.QScrollArea(self.mdl_grp_fix)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.lbl_mdl_fix = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_mdl_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_mdl_fix.setObjectName(_fromUtf8("lbl_mdl_fix"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mdl_grp_reference = QtGui.QGroupBox(self.tab_modeling)
        self.mdl_grp_reference.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference.setObjectName(_fromUtf8("mdl_grp_reference"))
        self.scrollArea_2 = QtGui.QScrollArea(self.mdl_grp_reference)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.lbl_mdl_reference = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.lbl_mdl_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_mdl_reference.setObjectName(_fromUtf8("lbl_mdl_reference"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabs_master.addTab(self.tab_modeling, _fromUtf8(""))
        self.tab_rig = QtGui.QWidget()
        self.tab_rig.setObjectName(_fromUtf8("tab_rig"))
        self.rig_grp_Scan = QtGui.QGroupBox(self.tab_rig)
        self.rig_grp_Scan.setGeometry(QtCore.QRect(20, 20, 191, 271))
        self.rig_grp_Scan.setObjectName(_fromUtf8("rig_grp_Scan"))
        self.frame = QtGui.QFrame(self.rig_grp_Scan)
        self.frame.setGeometry(QtCore.QRect(10, 20, 171, 241))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chk_rig_reference = QtGui.QCheckBox(self.frame)
        self.chk_rig_reference.setObjectName(_fromUtf8("chk_rig_reference"))
        self.verticalLayout_2.addWidget(self.chk_rig_reference)
        self.chk_rig_unknown = QtGui.QCheckBox(self.frame)
        self.chk_rig_unknown.setAutoFillBackground(False)
        self.chk_rig_unknown.setObjectName(_fromUtf8("chk_rig_unknown"))
        self.verticalLayout_2.addWidget(self.chk_rig_unknown)
        self.chk_rig_invalidNames = QtGui.QCheckBox(self.frame)
        self.chk_rig_invalidNames.setObjectName(_fromUtf8("chk_rig_invalidNames"))
        self.verticalLayout_2.addWidget(self.chk_rig_invalidNames)
        self.mdl_grp_reference_2 = QtGui.QGroupBox(self.tab_rig)
        self.mdl_grp_reference_2.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference_2.setObjectName(_fromUtf8("mdl_grp_reference_2"))
        self.scrollArea_4 = QtGui.QScrollArea(self.mdl_grp_reference_2)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.lbl_rig_reference = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.lbl_rig_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_rig_reference.setObjectName(_fromUtf8("lbl_rig_reference"))
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.mdl_grp_fix_2 = QtGui.QGroupBox(self.tab_rig)
        self.mdl_grp_fix_2.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix_2.setObjectName(_fromUtf8("mdl_grp_fix_2"))
        self.scrollArea_3 = QtGui.QScrollArea(self.mdl_grp_fix_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.lbl_rig_fix = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_rig_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_rig_fix.setObjectName(_fromUtf8("lbl_rig_fix"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabs_master.addTab(self.tab_rig, _fromUtf8(""))
        self.tab_animation = QtGui.QWidget()
        self.tab_animation.setObjectName(_fromUtf8("tab_animation"))
        self.anim_grp_scan = QtGui.QGroupBox(self.tab_animation)
        self.anim_grp_scan.setGeometry(QtCore.QRect(20, 20, 191, 271))
        self.anim_grp_scan.setObjectName(_fromUtf8("anim_grp_scan"))
        self.frame_2 = QtGui.QFrame(self.anim_grp_scan)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 171, 241))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chk_anim_atom = QtGui.QCheckBox(self.frame_2)
        self.chk_anim_atom.setObjectName(_fromUtf8("chk_anim_atom"))
        self.verticalLayout_3.addWidget(self.chk_anim_atom)
        self.chk_anim_reference = QtGui.QCheckBox(self.frame_2)
        self.chk_anim_reference.setObjectName(_fromUtf8("chk_anim_reference"))
        self.verticalLayout_3.addWidget(self.chk_anim_reference)
        self.chk_anim_unknown = QtGui.QCheckBox(self.frame_2)
        self.chk_anim_unknown.setAutoFillBackground(False)
        self.chk_anim_unknown.setObjectName(_fromUtf8("chk_anim_unknown"))
        self.verticalLayout_3.addWidget(self.chk_anim_unknown)
        self.chk_anim_invalidNames = QtGui.QCheckBox(self.frame_2)
        self.chk_anim_invalidNames.setObjectName(_fromUtf8("chk_anim_invalidNames"))
        self.verticalLayout_3.addWidget(self.chk_anim_invalidNames)
        self.mdl_grp_reference_3 = QtGui.QGroupBox(self.tab_animation)
        self.mdl_grp_reference_3.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference_3.setObjectName(_fromUtf8("mdl_grp_reference_3"))
        self.scrollArea_6 = QtGui.QScrollArea(self.mdl_grp_reference_3)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName(_fromUtf8("scrollArea_6"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.lbl_anim_reference = QtGui.QLabel(self.scrollAreaWidgetContents_6)
        self.lbl_anim_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_anim_reference.setObjectName(_fromUtf8("lbl_anim_reference"))
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.mdl_grp_fix_3 = QtGui.QGroupBox(self.tab_animation)
        self.mdl_grp_fix_3.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix_3.setObjectName(_fromUtf8("mdl_grp_fix_3"))
        self.scrollArea_5 = QtGui.QScrollArea(self.mdl_grp_fix_3)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.lbl_anim_fix = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.lbl_anim_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_anim_fix.setObjectName(_fromUtf8("lbl_anim_fix"))
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.tabs_master.addTab(self.tab_animation, _fromUtf8(""))
        self.tab_lighting = QtGui.QWidget()
        self.tab_lighting.setObjectName(_fromUtf8("tab_lighting"))
        self.grp_Scan_5 = QtGui.QGroupBox(self.tab_lighting)
        self.grp_Scan_5.setGeometry(QtCore.QRect(20, 20, 191, 271))
        self.grp_Scan_5.setObjectName(_fromUtf8("grp_Scan_5"))
        self.frame_3 = QtGui.QFrame(self.grp_Scan_5)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 171, 241))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.chk_light_external = QtGui.QCheckBox(self.frame_3)
        self.chk_light_external.setObjectName(_fromUtf8("chk_light_external"))
        self.verticalLayout_4.addWidget(self.chk_light_external)
        self.chk_light_reference = QtGui.QCheckBox(self.frame_3)
        self.chk_light_reference.setObjectName(_fromUtf8("chk_light_reference"))
        self.verticalLayout_4.addWidget(self.chk_light_reference)
        self.chk_light_unknown = QtGui.QCheckBox(self.frame_3)
        self.chk_light_unknown.setAutoFillBackground(False)
        self.chk_light_unknown.setObjectName(_fromUtf8("chk_light_unknown"))
        self.verticalLayout_4.addWidget(self.chk_light_unknown)
        self.chk_light_invalidNames = QtGui.QCheckBox(self.frame_3)
        self.chk_light_invalidNames.setObjectName(_fromUtf8("chk_light_invalidNames"))
        self.verticalLayout_4.addWidget(self.chk_light_invalidNames)
        self.mdl_grp_reference_4 = QtGui.QGroupBox(self.tab_lighting)
        self.mdl_grp_reference_4.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference_4.setObjectName(_fromUtf8("mdl_grp_reference_4"))
        self.scrollArea_8 = QtGui.QScrollArea(self.mdl_grp_reference_4)
        self.scrollArea_8.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName(_fromUtf8("scrollArea_8"))
        self.scrollAreaWidgetContents_8 = QtGui.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_8.setObjectName(_fromUtf8("scrollAreaWidgetContents_8"))
        self.lbl_light_reference = QtGui.QLabel(self.scrollAreaWidgetContents_8)
        self.lbl_light_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_light_reference.setObjectName(_fromUtf8("lbl_light_reference"))
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.mdl_grp_fix_4 = QtGui.QGroupBox(self.tab_lighting)
        self.mdl_grp_fix_4.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix_4.setObjectName(_fromUtf8("mdl_grp_fix_4"))
        self.scrollArea_7 = QtGui.QScrollArea(self.mdl_grp_fix_4)
        self.scrollArea_7.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName(_fromUtf8("scrollArea_7"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.lbl_light_fix = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.lbl_light_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_light_fix.setObjectName(_fromUtf8("lbl_light_fix"))
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.tabs_master.addTab(self.tab_lighting, _fromUtf8(""))
        self.tab_shading = QtGui.QWidget()
        self.tab_shading.setObjectName(_fromUtf8("tab_shading"))
        self.grp_Scan_4 = QtGui.QGroupBox(self.tab_shading)
        self.grp_Scan_4.setGeometry(QtCore.QRect(20, 20, 191, 271))
        self.grp_Scan_4.setObjectName(_fromUtf8("grp_Scan_4"))
        self.frame_4 = QtGui.QFrame(self.grp_Scan_4)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 171, 251))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.chk_shd_repeated = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_repeated.setObjectName(_fromUtf8("chk_shd_repeated"))
        self.verticalLayout_5.addWidget(self.chk_shd_repeated)
        self.chk_shd_external = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_external.setObjectName(_fromUtf8("chk_shd_external"))
        self.verticalLayout_5.addWidget(self.chk_shd_external)
        self.chk_shd_reference = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_reference.setObjectName(_fromUtf8("chk_shd_reference"))
        self.verticalLayout_5.addWidget(self.chk_shd_reference)
        self.chk_shd_textures = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_textures.setObjectName(_fromUtf8("chk_shd_textures"))
        self.verticalLayout_5.addWidget(self.chk_shd_textures)
        self.chk_shd_unknown = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_unknown.setAutoFillBackground(False)
        self.chk_shd_unknown.setObjectName(_fromUtf8("chk_shd_unknown"))
        self.verticalLayout_5.addWidget(self.chk_shd_unknown)
        self.chk_shd_invalidNames = QtGui.QCheckBox(self.frame_4)
        self.chk_shd_invalidNames.setObjectName(_fromUtf8("chk_shd_invalidNames"))
        self.verticalLayout_5.addWidget(self.chk_shd_invalidNames)
        self.mdl_grp_reference_5 = QtGui.QGroupBox(self.tab_shading)
        self.mdl_grp_reference_5.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference_5.setObjectName(_fromUtf8("mdl_grp_reference_5"))
        self.scrollArea_10 = QtGui.QScrollArea(self.mdl_grp_reference_5)
        self.scrollArea_10.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName(_fromUtf8("scrollArea_10"))
        self.scrollAreaWidgetContents_10 = QtGui.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_10.setObjectName(_fromUtf8("scrollAreaWidgetContents_10"))
        self.lbl_shd_reference = QtGui.QLabel(self.scrollAreaWidgetContents_10)
        self.lbl_shd_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_shd_reference.setObjectName(_fromUtf8("lbl_shd_reference"))
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_10)
        self.mdl_grp_fix_5 = QtGui.QGroupBox(self.tab_shading)
        self.mdl_grp_fix_5.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix_5.setObjectName(_fromUtf8("mdl_grp_fix_5"))
        self.scrollArea_9 = QtGui.QScrollArea(self.mdl_grp_fix_5)
        self.scrollArea_9.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName(_fromUtf8("scrollArea_9"))
        self.scrollAreaWidgetContents_9 = QtGui.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents_9.setObjectName(_fromUtf8("scrollAreaWidgetContents_9"))
        self.lbl_shd_fix = QtGui.QLabel(self.scrollAreaWidgetContents_9)
        self.lbl_shd_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_shd_fix.setObjectName(_fromUtf8("lbl_shd_fix"))
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.tabs_master.addTab(self.tab_shading, _fromUtf8(""))
        self.tab_vfx = QtGui.QWidget()
        self.tab_vfx.setObjectName(_fromUtf8("tab_vfx"))
        self.grp_Scan_6 = QtGui.QGroupBox(self.tab_vfx)
        self.grp_Scan_6.setGeometry(QtCore.QRect(20, 20, 191, 271))
        self.grp_Scan_6.setObjectName(_fromUtf8("grp_Scan_6"))
        self.frame_5 = QtGui.QFrame(self.grp_Scan_6)
        self.frame_5.setGeometry(QtCore.QRect(10, 20, 131, 241))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.chk_vfx_reference = QtGui.QCheckBox(self.frame_5)
        self.chk_vfx_reference.setObjectName(_fromUtf8("chk_vfx_reference"))
        self.verticalLayout_6.addWidget(self.chk_vfx_reference)
        self.chk_vfx_unknown = QtGui.QCheckBox(self.frame_5)
        self.chk_vfx_unknown.setAutoFillBackground(False)
        self.chk_vfx_unknown.setObjectName(_fromUtf8("chk_vfx_unknown"))
        self.verticalLayout_6.addWidget(self.chk_vfx_unknown)
        self.chk_vfx_invalidNames = QtGui.QCheckBox(self.frame_5)
        self.chk_vfx_invalidNames.setObjectName(_fromUtf8("chk_vfx_invalidNames"))
        self.verticalLayout_6.addWidget(self.chk_vfx_invalidNames)
        self.mdl_grp_reference_6 = QtGui.QGroupBox(self.tab_vfx)
        self.mdl_grp_reference_6.setGeometry(QtCore.QRect(240, 210, 221, 81))
        self.mdl_grp_reference_6.setObjectName(_fromUtf8("mdl_grp_reference_6"))
        self.scrollArea_12 = QtGui.QScrollArea(self.mdl_grp_reference_6)
        self.scrollArea_12.setGeometry(QtCore.QRect(0, 20, 221, 61))
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollArea_12.setObjectName(_fromUtf8("scrollArea_12"))
        self.scrollAreaWidgetContents_12 = QtGui.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 219, 59))
        self.scrollAreaWidgetContents_12.setObjectName(_fromUtf8("scrollAreaWidgetContents_12"))
        self.lbl_vfx_reference = QtGui.QLabel(self.scrollAreaWidgetContents_12)
        self.lbl_vfx_reference.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.lbl_vfx_reference.setObjectName(_fromUtf8("lbl_vfx_reference"))
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_12)
        self.mdl_grp_fix_6 = QtGui.QGroupBox(self.tab_vfx)
        self.mdl_grp_fix_6.setGeometry(QtCore.QRect(240, 20, 221, 171))
        self.mdl_grp_fix_6.setObjectName(_fromUtf8("mdl_grp_fix_6"))
        self.scrollArea_11 = QtGui.QScrollArea(self.mdl_grp_fix_6)
        self.scrollArea_11.setGeometry(QtCore.QRect(0, 20, 221, 151))
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName(_fromUtf8("scrollArea_11"))
        self.scrollAreaWidgetContents_11 = QtGui.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents_11.setObjectName(_fromUtf8("scrollAreaWidgetContents_11"))
        self.lbl_vfx_fix = QtGui.QLabel(self.scrollAreaWidgetContents_11)
        self.lbl_vfx_fix.setGeometry(QtCore.QRect(10, 10, 181, 131))
        self.lbl_vfx_fix.setObjectName(_fromUtf8("lbl_vfx_fix"))
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_11)
        self.tabs_master.addTab(self.tab_vfx, _fromUtf8(""))
        self.btn_Check = QtGui.QPushButton(self.centralwidget)
        self.btn_Check.setGeometry(QtCore.QRect(30, 150, 75, 23))
        self.btn_Check.setObjectName(_fromUtf8("btn_Check"))
        self.btn_Ok = QtGui.QPushButton(self.centralwidget)
        self.btn_Ok.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.btn_Ok.setObjectName(_fromUtf8("btn_Ok"))
        self.btn_details = QtGui.QPushButton(self.centralwidget)
        self.btn_details.setGeometry(QtCore.QRect(560, 420, 75, 23))
        self.btn_details.setObjectName(_fromUtf8("btn_details"))
        self.chk_box_checkall = QtGui.QPushButton(self.centralwidget)
        self.chk_box_checkall.setGeometry(QtCore.QRect(190, 420, 75, 23))
        self.chk_box_checkall.setObjectName(_fromUtf8("chk_box_checkall"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_master.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Maya scenes debuger", None))
        self.mdl_grp_scan.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_mdl_transformation.setText(_translate("MainWindow", "Transformations", None))
        self.chk_mdl_history.setText(_translate("MainWindow", "History", None))
        self.chk_mdl_hierarchy.setText(_translate("MainWindow", "Hierarchy", None))
        self.chk_mdl_names.setText(_translate("MainWindow", "Names", None))
        self.chk_mdl_materials.setText(_translate("MainWindow", "Materials", None))
        self.chk_mdl_uvSets.setText(_translate("MainWindow", "UV Sets", None))
        self.chk_mdl_center.setText(_translate("MainWindow", "Center", None))
        self.chk_mdl_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_mdl_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_fix.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_mdl_fix.setText(_translate("MainWindow", "Modeling Elements with problems.", None))
        self.mdl_grp_reference.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_mdl_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_modeling), _translate("MainWindow", "Modeling", None))
        self.rig_grp_Scan.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_rig_reference.setText(_translate("MainWindow", "Non referenced", None))
        self.chk_rig_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_rig_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_reference_2.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_rig_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.mdl_grp_fix_2.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_rig_fix.setText(_translate("MainWindow", "Rigging Elements with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_rig), _translate("MainWindow", "Rig", None))
        self.anim_grp_scan.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_anim_atom.setText(_translate("MainWindow", "Atom Nodes", None))
        self.chk_anim_reference.setText(_translate("MainWindow", "Non referenced", None))
        self.chk_anim_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_anim_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_reference_3.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_anim_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.mdl_grp_fix_3.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_anim_fix.setText(_translate("MainWindow", "Animation Elements with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_animation), _translate("MainWindow", "Animation", None))
        self.grp_Scan_5.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_light_external.setText(_translate("MainWindow", "External lights", None))
        self.chk_light_reference.setText(_translate("MainWindow", "Non referenced", None))
        self.chk_light_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_light_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_reference_4.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_light_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.mdl_grp_fix_4.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_light_fix.setText(_translate("MainWindow", "Lighting Elements with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_lighting), _translate("MainWindow", "Lighting", None))
        self.grp_Scan_4.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_shd_repeated.setText(_translate("MainWindow", "Repeated shaders", None))
        self.chk_shd_external.setText(_translate("MainWindow", "External shaders", None))
        self.chk_shd_reference.setText(_translate("MainWindow", "Non referenced", None))
        self.chk_shd_textures.setText(_translate("MainWindow", "Local Textures", None))
        self.chk_shd_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_shd_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_reference_5.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_shd_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.mdl_grp_fix_5.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_shd_fix.setText(_translate("MainWindow", "Shading Elements with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_shading), _translate("MainWindow", "Shading", None))
        self.grp_Scan_6.setTitle(_translate("MainWindow", "Scan", None))
        self.chk_vfx_reference.setText(_translate("MainWindow", "Non referenced", None))
        self.chk_vfx_unknown.setText(_translate("MainWindow", "Unknown Nodes", None))
        self.chk_vfx_invalidNames.setText(_translate("MainWindow", "Invalid Names", None))
        self.mdl_grp_reference_6.setTitle(_translate("MainWindow", "Reference problem", None))
        self.lbl_vfx_reference.setText(_translate("MainWindow", "References with problems.", None))
        self.mdl_grp_fix_6.setTitle(_translate("MainWindow", "Fix", None))
        self.lbl_vfx_fix.setText(_translate("MainWindow", "VFX Elements with problems.", None))
        self.tabs_master.setTabText(self.tabs_master.indexOf(self.tab_vfx), _translate("MainWindow", "VFX", None))
        self.btn_Check.setText(_translate("MainWindow", "Check", None))
        self.btn_Ok.setText(_translate("MainWindow", "Fix", None))
        self.btn_details.setText(_translate("MainWindow", "Details", None))
        self.chk_box_checkall.setText(_translate("MainWindow", "Check all", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))

